# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host:  aa1g8aybypoby55.cxjcbxordxn6.us-east-1.rds.amazonaws.com
  database: csinteligente_development_api
  username: root
  password: CS1nt3l1g3nt32018$$
  port: 5432

 
test:
  <<: *default
  host:  aa1g8aybypoby55.cxjcbxordxn6.us-east-1.rds.amazonaws.com
  database: csinteligente_test_api
  username: root
  password: CS1nt3l1g3nt32018$$
  port: 5432

production:
  <<: *default
  host:  aa1g8aybypoby55.cxjcbxordxn6.us-east-1.rds.amazonaws.com
  database: csinteligente_production_api
  username: root
  password: CS1nt3l1g3nt32018$$
  port: 5432
